// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package dicom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Strings-0]
	_ = x[Bytes-1]
	_ = x[Ints-2]
	_ = x[UInts-3]
	_ = x[PixelData-4]
	_ = x[SequenceItem-5]
	_ = x[Sequences-6]
	_ = x[Floats-7]
}

const _ValueType_name = "StringsBytesIntsUIntsPixelDataSequenceItemSequencesFloats"

var _ValueType_index = [...]uint8{0, 7, 12, 16, 21, 30, 42, 51, 57}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
